feat(bingAds): add UET ecomm fields
rudderlabs/rudder-sdk-js pull request #1048
Opened 2023-04-28 13:35 UTC by Gauravudia

## PR Description

Add UET ecomm fields

## Notion ticket

[Ticket link](https://www.notion.so/rudderstacks/Bing-Ads-Ecomm-53d104e3b79448bb98fa2d926a85cf80)

## Screenshots

Please add screenshots for any new features or UI bug fixes for the following browsers -

- Chrome
  >
- Firefox
  >
- Safari
  >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2023-05-02 04:32 UTC, MoumitaM requested changes

2023-05-02 04:32 UTC, MoumitaM commented on src/integrations/BingAds/browser.js
Replace line 25 with 
`(o.q = w[u]), (w[u] = w.UET ? new UET(o) : []);`

2023-05-02 04:32 UTC, MoumitaM commented on src/integrations/BingAds/browser.js
Line 49 
Update the logger message to something like this:
`logger.debug('Trying to load BingAds: https://bat.bing.com/bat.js');`

2023-05-02 04:42 UTC, MoumitaM commented on src/integrations/BingAds/browser.js
Addressed in Different PR

2023-05-02 04:42 UTC, MoumitaM commented on src/integrations/BingAds/browser.js
Addressed in Different PR

2023-05-02 04:42 UTC, MoumitaM reviewed
LGTM

2023-05-02 04:43 UTC, MoumitaM approved these changes

2023-05-04 09:10 UTC, Gauravudia commented on src/integrations/BingAds/utils.js
> +      if (product) {
we can remove this. As we have a check on product id on line 44.

2023-05-04 12:26 UTC, Gauravudia commented on src/integrations/BingAds/utils.js
> +      if (product) {
updated

2023-05-08 05:39 UTC, ItsSudip approved these changes

2023-05-09 02:40 UTC, sandeepdsvs approved these changes

2023-05-09 08:40 UTC, merged