feat: introduce flexible configuration for maximum buffering time of data plane events
rudderlabs/rudder-sdk-js pull request #1116
Opened 2023-05-30 05:53 UTC by mihir-4116

## PR Description

Please include a summary of the change along with the relevant motivation and context.

## Notion ticket

Ticket link

## Screenshots

Please add screenshots for any new features or UI bug fixes for the following browsers -

- Chrome
  >
- Firefox
  >
- Safari
  >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2023-05-31 04:51 UTC, saikumarrs requested changes

2023-05-31 04:51 UTC, saikumarrs commented on src/utils/constants.js
> +const DATA_PLANE_EVENTS_BUFFER_TIME_OUT = 10000;
```suggestion
const DATA_PLANE_EVENTS_BUFFER_TIMEOUT_MS = 10000;
```

2023-05-31 05:47 UTC, MoumitaM commented on src/utils/constants.js
> +const DATA_PLANE_EVENTS_BUFFER_TIME_OUT = 10000;
I will suggest `DEFAULT_DATA_PLANE_EVENTS_BUFFER_TIMEOUT_MS`.

2023-05-31 08:40 UTC, utsabc approved these changes

2023-05-31 08:40 UTC, utsabc submitted a review, later dismissed

2023-05-31 10:39 UTC, mihir-4116 commented on src/utils/constants.js
> +const DATA_PLANE_EVENTS_BUFFER_TIME_OUT = 10000;
updated variable name

2023-06-01 05:30 UTC, saikumarrs approved these changes

2023-06-02 05:00 UTC, MoumitaM approved these changes

2023-06-05 04:45 UTC, utsabc approved these changes

2023-06-05 05:08 UTC, merged