chore: adobe snippets moved to assets directory
rudderlabs/rudder-sdk-js pull request #1272
Opened 2023-08-02 07:39 UTC by yashasvibajpai

## PR Description

> Moving the cdn deployed analytics.js and heartbeat.js to cdn.

## Notion ticket

Ticket link

## Screenshots

Please add screenshots for any new features or UI bug fixes for the following browsers -

- Chrome
  >
- Firefox
  >
- Safari
  >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2023-08-02 11:02 UTC, bardisg requested changes
These assets are deployed to https://s3.console.aws.amazon.com/s3/buckets/rudderlabs-cdn?region=us-east-1&prefix=adobe-analytics-js/&showversions=false 

This is the adobe-analytics-js in cdn.

Lets add them in src/assets/adobe-analytics-js so we can separate them for deployment in case more assets come in the future

You also need to exclude frim sonar scan in the src/assets folder in all scans

2023-08-02 11:51 UTC, yashasvibajpai commented
> Apologies @yashasvibajpai can we move assets folder outside src? easier to exclude from all our tooling like that

Sure, should I keep assets in root or inside /public

2023-08-03 04:47 UTC, MoumitaM approved these changes

2023-08-03 11:27 UTC, bardisg approved these changes

2023-08-03 11:38 UTC, merged