feat: configure cookie to be fetched from exact domain
rudderlabs/rudder-sdk-js pull request #1468
Opened 2023-10-25 11:41 UTC by MoumitaM

## PR Description

Please include a summary of the change along with the relevant motivation and context.

## Linear task (optional)

Linear task link

## Cross Browser Tests

Please confirm you have tested for the following browsers:

- [ ] Chrome
- [ ] Firefox
- [ ] IE11

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2023-10-26 06:13 UTC, saikumarrs submitted a review, later dismissed

2023-10-26 16:25 UTC, bardisg commented
@MoumitaM does this cover both not adding cookies in top domain and not reading values from top domain if the new flag is true?

2023-10-27 03:39 UTC, MoumitaM commented
> @MoumitaM does this cover both not adding cookies in top domain and not reading values from top domain if the new flag is true?
With this feature, cookies will only be set from the current exact domain and read from that domain only. Say cookies set in testwebsite.com can only be accessed by testwebsite.com not by any other sub domains. The same is true for sub domains also.

2023-10-27 04:19 UTC, saikumarrs requested changes

2023-10-27 04:19 UTC, saikumarrs commented on packages/analytics-js-common/src/types/LoadOptions.ts
> +  sameDomainCookieOnly?: boolean;
```suggestion
  sameDomainCookiesOnly?: boolean;
```

2023-10-27 04:36 UTC, MoumitaM commented on packages/analytics-js-common/src/types/LoadOptions.ts
> +  sameDomainCookieOnly?: boolean;
Done

2023-10-27 04:37 UTC, saikumarrs approved these changes

2023-10-27 06:50 UTC, bardisg approved these changes

2023-10-27 06:55 UTC, merged