added logic for showing warning when reserved keywords ae sent in pro…
rudderlabs/rudder-sdk-js pull request #181
Opened 2021-01-04 11:07 UTC by ruchiramoitra

…perties/traits

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-01-04 12:16 UTC, arnab-p requested changes

2021-01-04 12:16 UTC, arnab-p commented on utils/constants.js
> +  reservedPropKeywords,
We should maintain the naming convention - `ReservedPropertyKeywords`

2021-01-04 12:16 UTC, arnab-p commented on analytics.js
> +        console.error(`Warning! : Reserved keyword used --> ${property} with page call for name --> ${name}`);
Should we use `logger` here and use a `warning` log level instead of `console.error`?

2021-01-04 12:23 UTC, sayan-mitra requested changes
Give the PR on staging

2021-01-04 12:23 UTC, sayan-mitra commented on analytics.js
> +    Object.keys(properties).forEach((property) => {
add a util function and pass props/traits as parameter ?
also can this check be done at a central loc like in https://github.com/rudderlabs/rudder-sdk-js/blob/production/analytics.js#L638

2021-01-04 12:23 UTC, sayan-mitra commented on analytics.js
> +        console.error(`Warning! : Reserved keyword used --> ${property} with track call for event --> ${event}`);
logger.error should be fine I think
other levels probably needs a wrapper/polyfill for support in older browsers

2021-01-07 03:19 UTC, sayan-mitra commented
closing this as #184  has the changes

2021-01-07 03:19 UTC, closed without merging