Klaviyo integration
rudderlabs/rudder-sdk-js pull request #212
Opened 2021-02-24 13:13 UTC by utsabc

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-02-25 07:22 UTC, sayan-mitra requested changes

2021-02-25 07:22 UTC, sayan-mitra commented on integrations/Klaviyo/browser.js
> +    if (
change as discussed

2021-02-25 11:15 UTC, utsabc commented on integrations/Klaviyo/browser.js
> +    if (
fixed

2021-02-25 11:15 UTC, utsabc commented on integrations/Klaviyo/browser.js
> +      window._learnq.push(["track", message.event, message.properties]);
done

2021-02-25 11:15 UTC, utsabc commented on integrations/Klaviyo/browser.js
> +      $id: message.userId,
done

2021-02-25 11:17 UTC, utsabc commented on integrations/Klaviyo/browser.js
> +        ["context.traits", "traits"],
done

2021-02-25 11:17 UTC, utsabc commented on utils/utils.js
> +      Object.keys(messageContext).map((value) => {
fixed

2021-02-25 11:17 UTC, utsabc commented on utils/utils.js
> +      const values = [];
fixed

2021-02-25 15:46 UTC, sayan-mitra requested changes

2021-02-25 15:46 UTC, sayan-mitra commented on integrations/Klaviyo/browser.js
> +        window._learnq.push(["track", `${pStr} ${catStr}`]);
should be infoString ?

2021-02-25 15:46 UTC, sayan-mitra commented on integrations/Klaviyo/browser.js
> +        window._learnq.push(["track", `${pStr} ${catStr}`]);
also, let's do something like ?

```
if (pageCategory && pageName) {
      eventName = `Viewed ${pageCategory} ${pageName} page`;
    }
    
else if (pageName) {
      eventName = `Viewed ${pageName} page`;
    }
else {
      eventName = "Viewed a Page";
    }
```

2021-02-25 15:46 UTC, sayan-mitra commented on utils/utils.js
> +// Extract fileds from message with exclusions
lets add doc under /** ... */

2021-02-25 15:46 UTC, sayan-mitra commented on integrations/Klaviyo/browser.js
> +        [
let's make this a const for the class
and use that in other places?

2021-02-25 15:46 UTC, sayan-mitra commented
Resolve conflict

2021-03-01 05:03 UTC, sayan-mitra commented on integrations/Klaviyo/browser.js
> +    } else {
is this else block required ?

2021-03-01 06:10 UTC, sayan-mitra commented on integrations/Klaviyo/browser.js
> +    } else {
as discussed, keeping it is fine

2021-03-01 06:10 UTC, sayan-mitra approved these changes

2021-03-01 06:10 UTC, utsabc commented on integrations/Klaviyo/browser.js
> +    } else {
resolved as discussed

2021-03-01 06:10 UTC, merged