Updated structure and revamped content
rudderlabs/rudder-sdk-js pull request #350
Opened 2021-10-05 07:30 UTC by ameypv-rudder

## Description of the change

> Refreshed the readme content as per the latest doc changes.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-10-05 08:08 UTC, saikumarrs commented
Along the same lines, please update README.md in dist\rudder-sdk-js as well. This is for the SDK NPM package.

2021-10-05 08:19 UTC, saikumarrs submitted a review, later dismissed

2021-10-06 03:37 UTC, ameypv-rudder commented
> Along the same lines, please update README.md in dist\rudder-sdk-js as well. This is for the SDK NPM package.

thanks for your inputs, Sai, this is now done.

2021-10-06 07:13 UTC, saikumarrs requested changes

2021-10-06 07:13 UTC, saikumarrs commented on dist/rudder-sdk-js/README.md
> +### How to build the SDK
This section is applicable only for repository readme file whereas this is bundled with the distribution package. Please remove it.

2021-10-06 09:20 UTC, saikumarrs approved these changes

2021-10-07 09:17 UTC, merged