Feat: altering page event name
rudderlabs/rudder-sdk-js pull request #369
Opened 2021-11-03 11:11 UTC by ItsSudip

Here we are adding support for segment like page event call. Before it we used to call the event with 'Viewed page ****' but now will call the event with 'Viewed ***** Page', if 'alterPageEventName' is set to true in options.

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-11-03 13:28 UTC, saikumarrs requested changes

2021-11-03 13:28 UTC, saikumarrs commented on integrations/Amplitude/browser.js
> +    const { alterPageEventName } = rudderElement.message.context;
Let's rename it to something like "useNewPageEventNameFormat"

2021-11-03 13:28 UTC, saikumarrs commented on integrations/Amplitude/browser.js
>        amplitude.getInstance().logEvent(event, properties);
Minor re-factor
- localize `event` variable to the `if` blocks
- To improve readability 
`let event = "Viewed Page Category";
    if (<flag>) event = "Viewed Category Page"`

2021-11-05 06:02 UTC, akashrpo commented
LGTM

2021-11-05 06:14 UTC, saikumarrs submitted a review, later dismissed

2021-11-10 11:11 UTC, MoumitaM submitted a review, later dismissed

2021-11-10 11:45 UTC, saikumarrs approved these changes

2021-11-10 11:46 UTC, merged