Single source integration names
rudderlabs/rudder-sdk-js pull request #442
Opened 2022-01-31 09:44 UTC by MoumitaM

## Description of the change

> Import the name of the device-mode integrations from the integration_to_cname file. So that there will be a single source for integration names.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-31 11:11 UTC, saikumarrs requested changes

2022-01-31 11:11 UTC, saikumarrs commented on integrations/AdobeAnalytics/browser.js
> +import { commonNames } from "../integration_cname";
This way we can detect errors at build time.
```suggestion
import { commonNames.ADOBE_ANALYTICS as NAME } from "../integration_cname";
```

2022-02-01 12:26 UTC, MoumitaM commented
This approach will increase the core SDK size significantly.

2022-02-03 06:19 UTC, saikumarrs approved these changes

2022-02-03 06:19 UTC, merged