Fix: handled undefined integration obj error
rudderlabs/rudder-sdk-js pull request #551
Opened 2022-06-30 09:38 UTC by MoumitaM

## Description of the change

- handled undefined integration obj error
- Updated console APIs in logUtil

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/551)

2022-06-30 14:18 UTC, saikumarrs requested changes

2022-07-01 09:35 UTC, MoumitaM commented on analytics.js
> +        tranformToRudderNames(integrations);
In case, someone sends 
{integrations:12345}
Then it will pass.

2022-07-01 09:41 UTC, saikumarrs commented on analytics.js
> +        tranformToRudderNames(integrations);
Yes, but there won't be any error.

2022-07-01 11:06 UTC, saikumarrs approved these changes

2022-07-02 08:34 UTC, merged