feat(new integration): Engage - onboard integration
rudderlabs/rudder-sdk-js pull request #672
Opened 2022-09-30 11:23 UTC by anantjain45823

## Description of the change

> Onboarding Engaging Destination

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-10-01 05:38 UTC, MoumitaM commented
In order for logger module to work add the below code in browser.js.
1. Add **analytics** in the constructor
`constructor(config, analytics) {`
2. Add the below code in the constructor.
    `if (analytics.logLevel) {
      logger.setLogLevel(analytics.logLevel);
    }`

2022-10-01 05:39 UTC, MoumitaM requested changes
In order for logger module to work add the below code in browser.js.
1. Add **analytics** in the constructor
`constructor(config, analytics) {`
2. Add the below code in the constructor.
    `if (analytics.logLevel) {
      logger.setLogLevel(analytics.logLevel);
    }`

2022-10-06 05:08 UTC, MoumitaM approved these changes

2022-10-06 05:11 UTC, shrouti1507 approved these changes

2022-10-06 05:49 UTC, merged