fix: common names map update
rudderlabs/rudder-sdk-js pull request #681
Opened 2022-10-14 13:14 UTC by anantjain45823

## Description of the change

> Common Names Map Update 
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/681)

2022-10-14 14:09 UTC, MoumitaM requested changes
Most of the mapping has repetitive values. Remove those values.

2022-10-14 14:09 UTC, MoumitaM commented on integrations/Adroll/constants.js
> +  ADROLL: NAME,
Line 5 is not needed as it is already present.

2022-10-14 14:09 UTC, MoumitaM commented on integrations/Appcues/constants.js
> +  APPCUES: NAME,
Not needed.

2022-10-14 14:09 UTC, MoumitaM commented on integrations/Braze/constants.js
> +  BRAZE: NAME,
Not needed. Instead Add "braze".

2022-10-17 06:32 UTC, MoumitaM approved these changes

2022-10-17 09:47 UTC, shrouti1507 approved these changes

2022-10-17 10:04 UTC, merged