feat: messageId format updated
rudderlabs/rudder-sdk-js pull request #684
Opened 2022-10-17 17:46 UTC by MoumitaM

## Description of the change

> Default logic for generating message Id updated from `timestamp+ uuid` to only `uuid`.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-10-17 17:51 UTC, saikumarrs requested changes

2022-10-18 07:32 UTC, MoumitaM commented on utils/RudderMessage.js
> +function generateMessageId(flag = false) {
Just wanted to keep the logic in case of future use. Updated the name of the flag.

2022-10-18 08:26 UTC, saikumarrs submitted a review, later dismissed

2022-11-02 17:19 UTC, MoumitaM commented
Not required anymore.

2022-11-15 08:56 UTC, bardisg commented
@MoumitaM is this ready to be reviewed based on latest requirements?

2022-11-16 06:05 UTC, MoumitaM commented
> @MoumitaM is this ready to be reviewed based on latest requirements?

Yes @bardisg

2022-11-22 09:06 UTC, bardisg approved these changes

2022-11-22 11:17 UTC, merged