feat(new integration): onboarding sendinblue web device mode destination
rudderlabs/rudder-sdk-js pull request #804
Opened 2022-12-15 07:57 UTC by Gauravudia

## PR Description

Onboarding Sendinblue web device mode destination

## Notion ticket

[Ticket link](https://www.notion.so/rudderstacks/SendinBlue-Device-Mode-Destination-f039bdd648c44be5ba857a4c851876b7#25cca8758ad04446b9ada78cb68ea656)

## Screenshots

Please add screenshots for any new features or UI bug fixes for the following browsers -

- Chrome
  >
<img width="1728" alt="Screenshot 2022-12-15 at 1 24 12 PM" src="https://user-images.githubusercontent.com/60897972/207803820-6666b8b7-2ad9-4ff2-ab34-2a286963b056.png">
<img width="1728" alt="Screenshot 2022-12-15 at 1 24 53 PM" src="https://user-images.githubusercontent.com/60897972/207803850-1441c55b-cf5f-41ed-82de-9c9d1cf836ad.png">
<img width="835" alt="Screenshot 2022-12-15 at 1 26 26 PM" src="https://user-images.githubusercontent.com/60897972/207804126-bd6b3704-727e-494f-8ccc-389a9ab502c1.png">

- Firefox
  >
- Safari
  >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2022-12-16 09:55 UTC, MoumitaM approved these changes

2023-01-04 06:09 UTC, MoumitaM approved these changes

2023-01-05 06:01 UTC, shrouti1507 submitted a review, later dismissed
Please solve the sonarlint error

2023-01-05 07:04 UTC, Gauravudia commented
> Please solve the sonarlint error

`Third party loading code snippet` comment added in sonarcloud.

2023-01-05 07:14 UTC, ItsSudip requested changes

2023-01-05 07:14 UTC, ItsSudip commented on src/integrations/Sendinblue/browser.js
> +      : {};
```suggestion
    let userTraits = {};
    if (this.sendTraitsInTrack) {
      const { phone } = getDefinedTraits(message);
      if (phone && !validatePhoneWithCountryCode(phone)) {
        logger.error('[Sendinblue]:: provided phone number is invalid');
        return;
      }
      userTraits = this.sendTraitsInTrack
      ? prepareUserTraits(message, this.contactAttributeMapping)
      : {};

    }

```

2023-01-05 08:28 UTC, Gauravudia commented on src/integrations/Sendinblue/browser.js
> +      : {};
updated

2023-01-05 09:29 UTC, ItsSudip approved these changes

2023-01-05 09:52 UTC, shrouti1507 approved these changes

2023-01-05 10:02 UTC, MoumitaM approved these changes

2023-01-05 11:00 UTC, merged